name: Basic CI

on: [pull_request]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run python script
        run: |
          pip install -r requirements.txt
          python ci.py
    
